# Set up for GitHub Actions, npm and Composer

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
    - "dependencies"
    open-pull-requests-limit: 50
    rebase-strategy: auto
    schedule:
      interval: "daily"
      time: "05:00"
    target-branch: "main"
    groups:
      github-actions:
        patterns:
          - "*"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    labels:
    - "dependencies"
    open-pull-requests-limit: 50
    rebase-strategy: auto
    schedule:
      interval: "daily"
      time: "05:00"
    target-branch: "main"
    versioning-strategy: increase
    groups:
      assets:
        patterns:
          - "bootstrap*"
          - "*popper*"
          - "font-awesome"
      build:
        exclude-patterns:
          - "bootstrap*"
          - "*popper*"
          - "font-awesome"

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    allow:
    - dependency-type: direct
    - dependency-type: indirect
    directory: "/"
    labels:
    - "dependencies"
    open-pull-requests-limit: 50
    rebase-strategy: auto
    schedule:
      interval: "daily"
      time: "05:00"
    target-branch: "main"
    versioning-strategy: increase
    groups:
      composer:
        patterns:
          - "*"
